### ISSUE TITLE
Add a new feed contributor for COTS

### ISSUE THREAD

**Issue by prhod** [CanalTP/kirin#145]
add the cots contributor in kirin parameters.
(check in default_settings.py : KIRIN_CONTRIBUTOR)

**Comment by pbougue** [comment]
This is delt with in default configuration (already merged) : https://github.com/CanalTP/kirin/pull/153/files#diff-c97f1f178c9f2aae829e5e5f5d4a7d85R29
The way to handle this is the same than IRE, we stay on default config, nothing more to handle in fab_kirin or deployment_conf.
