### ISSUE TITLE
Add conf for dev/internal/custo for COTS (navitia)

### ISSUE THREAD

**Issue by pbougue** [CanalTP/kirin#173]
1 PR for dev
1 PR for internal/customer
also do prod conf ('do_not_merge') once we are stable

**Comment by pbougue** [comment]
Removed the "v0" label as the part for v0 is now OK, it's deployed on custo.

**Comment by prhod** [comment]
I'm closing this issue, the configuration is OK and deployed.
We are waiting for a notice for a deployment in production (it will be traced in an other issue).
