### ISSUE TITLE
Contributor feed configuration with token

### ISSUE THREAD

**Issue by sign0** [CanalTP/kirin#339]
This is the first time I'm using Kirin and GTFS-RT protocol while trying to integrate this realtime feed (Ireland) :
[https://developer.nationaltransport.ie/api-details#api=gtfsr](https://developer.nationaltransport.ie/api-details#api=gtfsr)

Is it possible to store a key/value header to request a feed (eg. ```x-api-key: ...```) ?
Or is it up to me to manage this with a proxy ?

Thanks

**Comment by woshilapin** [comment]
This looks like an interesting and valid use case but, I believe, not one supported by Kirin so far.

A `Contributor` is configured with only a [`feed_url`](https://github.com/CanalTP/kirin/blob/480a66c26af6fa58638a21f958115c9faa6bc49b/kirin/core/model.py#L515) where you can put the URL. From what I can see [in the source code](https://github.com/CanalTP/kirin/blob/480a66c26af6fa58638a21f958115c9faa6bc49b/kirin/gtfs_rt/tasks.py#L118) when using this `feed_url`, the HTTP `GET` is done without anymore customization.

I don't believe we will have time to work on that kind of feature at the moment but if you're willing to contribute, we can probably provide guidance.

**Comment by pbougue** [comment]
Yep, no plan to make kirin super aware of identification patterns, but it's a feature that would fit OK in Kirin or in a proxy.

As for the feed you're planning to integrate, please keep in mind that GTFS-RT can be implemented in different ways and Kirin is not supporting it all currently. To check it, you can compare feed to what's provided by Sherbrooke's tripUpdate: http://gtfsrt.stsherbrooke.civilia.ca/pb/tripUpdates.pb . If you don't have the same fields provided you will most probably lack some information (see also spec https://github.com/CanalTP/kirin/blob/master/documentation/gtfsrt_connector.md).

**Comment by pbougue** [comment]
Closing this issue now.
There is still no plan to especially handle authent inside Kirin, but it's a valid idea.
As for the GTFSRT handling, this is not the main issue discussed here, but it's getting improvements currently.
